sonar.projectKey=K8s-Dashboard
sonar.projectName=K8s-Dashboard
sonar.sourceEncoding=UTF-8

# Go test files
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Skip binary/image assets
sonar.exclusions=docs/screenshots/**
